/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU;

import BD4.Conexion;
import BD4.ConsultasBD;
import Clases.Empleado;
import Clases.Especie;
import Clases.Mascota;
import Clases.Veterinario;
import static EDU.purdue.cs.bloat.tree.ArithExpr.AND;
import java.util.List;
import javax.swing.JOptionPane;



/**
 *
 * @author Efigenia
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    VentanaAdministrador ventana3 ;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        ventana3 = new VentanaAdministrador();
        initComponents();
        ventana3.setVisible(false);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContenedorPrincipal = new javax.swing.JPanel();
        BarradeHerramientas = new javax.swing.JPanel();
        Txt_Ingreso = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JButton();
        Txt_Ingreso1 = new javax.swing.JLabel();
        txt_Cedula = new javax.swing.JLabel();
        btn_Ingresar = new javax.swing.JButton();
        tF_Cedula = new javax.swing.JFormattedTextField();
        txt_Pass = new javax.swing.JLabel();
        tfPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Peluditos");
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        ContenedorPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        ContenedorPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        ContenedorPrincipal.setLayout(null);

        BarradeHerramientas.setBackground(new java.awt.Color(0, 153, 0));
        BarradeHerramientas.setLayout(null);

        Txt_Ingreso.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        Txt_Ingreso.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Ingreso.setText("         Clinica Peluditos Pet");
        Txt_Ingreso.setAlignmentX(0.5F);
        Txt_Ingreso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Txt_Ingreso.setInheritsPopupMenu(false);
        BarradeHerramientas.add(Txt_Ingreso);
        Txt_Ingreso.setBounds(30, 0, 320, 40);

        BotonSalir.setBackground(new java.awt.Color(0, 153, 0));
        BotonSalir.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalir.setText("X");
        BotonSalir.setContentAreaFilled(false);
        BotonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonSalir.setOpaque(true);
        BotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalirMouseExited(evt);
            }
        });
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        BarradeHerramientas.add(BotonSalir);
        BotonSalir.setBounds(340, 0, 60, 40);

        Txt_Ingreso1.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        Txt_Ingreso1.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Ingreso1.setText("Menu de Ingreso");
        Txt_Ingreso1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Txt_Ingreso1.setAlignmentX(0.5F);
        Txt_Ingreso1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BarradeHerramientas.add(Txt_Ingreso1);
        Txt_Ingreso1.setBounds(70, 60, 270, 40);

        ContenedorPrincipal.add(BarradeHerramientas);
        BarradeHerramientas.setBounds(1, 1, 398, 98);

        txt_Cedula.setBackground(new java.awt.Color(0, 102, 255));
        txt_Cedula.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        txt_Cedula.setForeground(new java.awt.Color(255, 0, 0));
        txt_Cedula.setText("Cedula:");
        txt_Cedula.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ContenedorPrincipal.add(txt_Cedula);
        txt_Cedula.setBounds(10, 130, 100, 30);

        btn_Ingresar.setBackground(new java.awt.Color(0, 153, 0));
        btn_Ingresar.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        btn_Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ingresar.setText("Ingresar");
        btn_Ingresar.setContentAreaFilled(false);
        btn_Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_Ingresar.setOpaque(true);
        btn_Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_IngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_IngresarMouseExited(evt);
            }
        });
        btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarActionPerformed(evt);
            }
        });
        ContenedorPrincipal.add(btn_Ingresar);
        btn_Ingresar.setBounds(140, 240, 110, 30);

        tF_Cedula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 1, true));
        tF_Cedula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tF_Cedula.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tF_Cedula.setText("26662966");
        tF_Cedula.setToolTipText("");
        tF_Cedula.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tF_Cedula.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        ContenedorPrincipal.add(tF_Cedula);
        tF_Cedula.setBounds(170, 130, 210, 30);

        txt_Pass.setBackground(new java.awt.Color(0, 102, 255));
        txt_Pass.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        txt_Pass.setForeground(new java.awt.Color(255, 0, 0));
        txt_Pass.setText("Contraseña:");
        txt_Pass.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ContenedorPrincipal.add(txt_Pass);
        txt_Pass.setBounds(10, 190, 150, 30);

        tfPass.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        tfPass.setText("7ggb7");
        tfPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        ContenedorPrincipal.add(tfPass);
        tfPass.setBounds(170, 190, 210, 30);

        getContentPane().add(ContenedorPrincipal);
        ContenedorPrincipal.setBounds(0, 0, 400, 300);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
        Conexion.cerrarBD();
    }//GEN-LAST:event_BotonSalirActionPerformed


    private void nologueado(){
        JOptionPane.showMessageDialog(null, "Acceso denegado: Los datos ingresados son incorrectos."
                                           , "Error", JOptionPane.ERROR_MESSAGE);
    }
    private void btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarActionPerformed
        String respuesta;
        String Pass;
        respuesta = tF_Cedula.getText();
        char[] arrayC = tfPass.getPassword();
        Pass = new String(arrayC);
   
        ConsultasBD.escribirEmpleado(ConsultasBD.obtenerEmpleado());
        ConsultasBD.escribirVeterinario(ConsultasBD.obtenerVeterinario());
        
            if( ConsultasBD.existeEmpleado(respuesta)){
                    Empleado trabajador = ConsultasBD.buscarEmpleado(respuesta).get(0);
                    System.out.println(Pass);
                    System.out.println(trabajador.getPass());
                    if(trabajador.getPass().equalsIgnoreCase(Pass)){
                         if(trabajador.gettEmpleado() == 1){
                            ventana3 = new VentanaAdministrador(trabajador.getCedula(),trabajador.gettEmpleado(),trabajador.getNombre());
                            this.setVisible(false);
                            ventana3.setVisible(true);
                        }
                        else
                        if( trabajador.gettEmpleado() ==2){
                            ventana3 = new VentanaAdministrador(trabajador.getCedula(),trabajador.gettEmpleado(),trabajador.getNombre());

                            this.setVisible(false);
                            ventana3.setVisible(true);
                        }
                        else
                        if( trabajador.gettEmpleado() == 3){
                            ventana3 = new VentanaAdministrador(trabajador.getCedula(),trabajador.gettEmpleado(),trabajador.getNombre());

                            this.setVisible(false);
                            ventana3.setVisible(true);
                        }
                    } else{
                        nologueado();
                    }
                    }
            else
            JOptionPane.showMessageDialog(null, "Acceso denegado: No existe el trabajador"
                                           , "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btn_IngresarActionPerformed

    private void BotonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseEntered
        BotonSalir.setBackground( new java.awt.Color (255,0,0) );
    }//GEN-LAST:event_BotonSalirMouseEntered

    private void BotonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseExited
        BotonSalir.setBackground( new java.awt.Color(0,153,0) );
    }//GEN-LAST:event_BotonSalirMouseExited

    private void btn_IngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IngresarMouseEntered
        btn_Ingresar.setBackground( new java.awt.Color (255,102,0) );
    }//GEN-LAST:event_btn_IngresarMouseEntered

    private void btn_IngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IngresarMouseExited
        btn_Ingresar.setBackground( new java.awt.Color(0,153,0) );
    }//GEN-LAST:event_btn_IngresarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarradeHerramientas;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JPanel ContenedorPrincipal;
    private javax.swing.JLabel Txt_Ingreso;
    private javax.swing.JLabel Txt_Ingreso1;
    private javax.swing.JButton btn_Ingresar;
    private javax.swing.JFormattedTextField tF_Cedula;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JLabel txt_Cedula;
    private javax.swing.JLabel txt_Pass;
    // End of variables declaration//GEN-END:variables
}
