/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IU;

import BD4.Conexion;
import BD4.ConsultasBD;
import IU.VentanasCrud.*;


/**
 *
 * @author Efigenia
 */
public class VentanaAdministrador extends javax.swing.JFrame {

    String cedula;
    String nombre;
    int permisos;
    
    private VistaEspecialidad especialidad;
    private VistaEspecie especie;
    private VistaServicios servicios;
    
    private VistaClientes clientes;
    private VistaEmpleado empleados;
    private VistaVeterinario veterinarios;
    
    private VistaMascota mascotas;
    private VistaConsultas consultas;
    private VistaFactura facturas;
    
    public VentanaAdministrador() {
        initComponents();
        initMiscomponentes();
        this.setLocationRelativeTo(null);
    }
    
    public VentanaAdministrador(String cedula,int permisos,String nombre) {
        this.cedula= cedula;
        this.nombre= nombre;
        this.permisos=permisos;
        initComponents();
        initMiscomponentes();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Principal = new javax.swing.JPanel();
        jp_BarraHerramientas = new javax.swing.JPanel();
        BotonSalir = new javax.swing.JButton();
        Txt_Ingreso = new javax.swing.JLabel();
        Txt_Ingreso1 = new javax.swing.JLabel();
        Txt_user = new javax.swing.JLabel();
        btnCliente = new javax.swing.JPanel();
        txt_imgCliente = new javax.swing.JLabel();
        txt_Cliente = new javax.swing.JLabel();
        btnVeterinario = new javax.swing.JPanel();
        txt_imgVeterinario = new javax.swing.JLabel();
        txt_Veterinario = new javax.swing.JLabel();
        btnEmpleado = new javax.swing.JPanel();
        txt_imgEmpleado = new javax.swing.JLabel();
        txt_Empleado = new javax.swing.JLabel();
        btnMascota = new javax.swing.JPanel();
        txt_imgMascota = new javax.swing.JLabel();
        txt_Cliente2 = new javax.swing.JLabel();
        btnConsulta = new javax.swing.JPanel();
        txt_imgConsultas = new javax.swing.JLabel();
        txt_Consulta = new javax.swing.JLabel();
        btnEspecies = new javax.swing.JPanel();
        txt_imgEspecies = new javax.swing.JLabel();
        txt_Especie = new javax.swing.JLabel();
        btnFactura = new javax.swing.JPanel();
        txt_imgFactura = new javax.swing.JLabel();
        txt_Factura = new javax.swing.JLabel();
        btnEspecialidad = new javax.swing.JPanel();
        txt_imgEspecialidad = new javax.swing.JLabel();
        txt_Especiali = new javax.swing.JLabel();
        btnServicio = new javax.swing.JPanel();
        txt_imgServicio = new javax.swing.JLabel();
        txt_Servicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administracion");
        setMinimumSize(new java.awt.Dimension(900, 700));
        setName("Ventana"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(null);

        jP_Principal.setBackground(new java.awt.Color(255, 255, 255));
        jP_Principal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 1, true));
        jP_Principal.setLayout(null);

        jp_BarraHerramientas.setBackground(new java.awt.Color(0, 153, 0));
        jp_BarraHerramientas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 0), 1, true));

        BotonSalir.setBackground(new java.awt.Color(0, 153, 0));
        BotonSalir.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalir.setText("X");
        BotonSalir.setContentAreaFilled(false);
        BotonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonSalir.setOpaque(true);
        BotonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonSalirMouseExited(evt);
            }
        });
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        Txt_Ingreso.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 24)); // NOI18N
        Txt_Ingreso.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Ingreso.setText("         Clinica Peluditos Pet");
        Txt_Ingreso.setAlignmentX(0.5F);
        Txt_Ingreso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Txt_Ingreso.setInheritsPopupMenu(false);

        Txt_Ingreso1.setFont(new java.awt.Font("Leelawadee UI", 0, 36)); // NOI18N
        Txt_Ingreso1.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Ingreso1.setText("Menu Principal");
        Txt_Ingreso1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Txt_Ingreso1.setAlignmentX(0.5F);
        Txt_Ingreso1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Txt_user.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        Txt_user.setForeground(new java.awt.Color(255, 255, 255));
        Txt_user.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Txt_user.setText("Bienvenid@ "+this.nombre);
        Txt_user.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Txt_user.setAlignmentX(0.5F);
        Txt_user.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jp_BarraHerramientasLayout = new javax.swing.GroupLayout(jp_BarraHerramientas);
        jp_BarraHerramientas.setLayout(jp_BarraHerramientasLayout);
        jp_BarraHerramientasLayout.setHorizontalGroup(
            jp_BarraHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_BarraHerramientasLayout.createSequentialGroup()
                .addGap(0, 252, Short.MAX_VALUE)
                .addComponent(Txt_Ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jp_BarraHerramientasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Txt_Ingreso1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jp_BarraHerramientasLayout.setVerticalGroup(
            jp_BarraHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_BarraHerramientasLayout.createSequentialGroup()
                .addGroup(jp_BarraHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_Ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_BarraHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_BarraHerramientasLayout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(Txt_Ingreso1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_BarraHerramientasLayout.createSequentialGroup()
                        .addComponent(Txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jP_Principal.add(jp_BarraHerramientas);
        jp_BarraHerramientas.setBounds(0, 0, 900, 100);

        btnCliente.setBackground(new java.awt.Color(255, 255, 255));
        btnCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClienteMouseExited(evt);
            }
        });
        btnCliente.setLayout(null);

        txt_imgCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cliente.png"))); // NOI18N
        btnCliente.add(txt_imgCliente);
        txt_imgCliente.setBounds(70, 0, 120, 80);

        txt_Cliente.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        txt_Cliente.setText("Clientes");
        txt_Cliente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnCliente.add(txt_Cliente);
        txt_Cliente.setBounds(50, 70, 100, 30);

        jP_Principal.add(btnCliente);
        btnCliente.setBounds(60, 160, 190, 100);

        btnVeterinario.setBackground(new java.awt.Color(255, 255, 255));
        btnVeterinario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVeterinario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVeterinarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVeterinarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVeterinarioMouseExited(evt);
            }
        });
        btnVeterinario.setLayout(null);

        txt_imgVeterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Veterinario.png"))); // NOI18N
        btnVeterinario.add(txt_imgVeterinario);
        txt_imgVeterinario.setBounds(90, 0, 130, 80);

        txt_Veterinario.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        txt_Veterinario.setText("Veterinarios");
        btnVeterinario.add(txt_Veterinario);
        txt_Veterinario.setBounds(50, 70, 140, 30);

        jP_Principal.add(btnVeterinario);
        btnVeterinario.setBounds(330, 160, 230, 100);

        btnEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        btnEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEmpleadoMouseExited(evt);
            }
        });
        btnEmpleado.setLayout(null);

        txt_imgEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Empleados.png"))); // NOI18N
        txt_imgEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmpleado.add(txt_imgEmpleado);
        txt_imgEmpleado.setBounds(70, 0, 120, 100);

        txt_Empleado.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        txt_Empleado.setText("Empleados");
        txt_Empleado.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEmpleado.add(txt_Empleado);
        txt_Empleado.setBounds(40, 70, 130, 30);

        jP_Principal.add(btnEmpleado);
        btnEmpleado.setBounds(650, 160, 190, 100);

        btnMascota.setBackground(new java.awt.Color(255, 255, 255));
        btnMascota.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMascotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMascotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMascotaMouseExited(evt);
            }
        });
        btnMascota.setLayout(null);

        txt_imgMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mascota.png"))); // NOI18N
        btnMascota.add(txt_imgMascota);
        txt_imgMascota.setBounds(70, 0, 110, 80);

        txt_Cliente2.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        txt_Cliente2.setText("Mascotas");
        txt_Cliente2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMascota.add(txt_Cliente2);
        txt_Cliente2.setBounds(40, 70, 120, 30);

        jP_Principal.add(btnMascota);
        btnMascota.setBounds(60, 320, 190, 100);

        btnConsulta.setBackground(new java.awt.Color(255, 255, 255));
        btnConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConsulta.setPreferredSize(new java.awt.Dimension(190, 100));
        btnConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultaMouseExited(evt);
            }
        });
        btnConsulta.setLayout(null);

        txt_imgConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Consulta.png"))); // NOI18N
        btnConsulta.add(txt_imgConsultas);
        txt_imgConsultas.setBounds(70, 0, 110, 80);

        txt_Consulta.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        txt_Consulta.setText("Consultas");
        btnConsulta.add(txt_Consulta);
        txt_Consulta.setBounds(40, 70, 140, 30);

        jP_Principal.add(btnConsulta);
        btnConsulta.setBounds(350, 320, 200, 100);

        btnEspecies.setBackground(new java.awt.Color(255, 255, 255));
        btnEspecies.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEspecies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEspeciesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEspeciesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEspeciesMouseExited(evt);
            }
        });
        btnEspecies.setLayout(null);

        txt_imgEspecies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Especies.png"))); // NOI18N
        btnEspecies.add(txt_imgEspecies);
        txt_imgEspecies.setBounds(70, 0, 120, 80);

        txt_Especie.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        txt_Especie.setText("Especies");
        txt_Especie.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnEspecies.add(txt_Especie);
        txt_Especie.setBounds(50, 70, 130, 30);

        jP_Principal.add(btnEspecies);
        btnEspecies.setBounds(650, 320, 190, 100);

        btnFactura.setBackground(new java.awt.Color(255, 255, 255));
        btnFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacturaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFacturaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFacturaMouseExited(evt);
            }
        });
        btnFactura.setLayout(null);

        txt_imgFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Factura.png"))); // NOI18N
        btnFactura.add(txt_imgFactura);
        txt_imgFactura.setBounds(70, 0, 120, 80);

        txt_Factura.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        txt_Factura.setText("Facturar");
        txt_Factura.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnFactura.add(txt_Factura);
        txt_Factura.setBounds(50, 50, 120, 50);

        jP_Principal.add(btnFactura);
        btnFactura.setBounds(60, 480, 190, 100);

        btnEspecialidad.setBackground(new java.awt.Color(255, 255, 255));
        btnEspecialidad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEspecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEspecialidadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEspecialidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEspecialidadMouseExited(evt);
            }
        });
        btnEspecialidad.setLayout(null);

        txt_imgEspecialidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Especialidad.png"))); // NOI18N
        btnEspecialidad.add(txt_imgEspecialidad);
        txt_imgEspecialidad.setBounds(90, 0, 130, 80);

        txt_Especiali.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        txt_Especiali.setText("Especialidad");
        btnEspecialidad.add(txt_Especiali);
        txt_Especiali.setBounds(40, 70, 160, 30);

        jP_Principal.add(btnEspecialidad);
        btnEspecialidad.setBounds(330, 480, 230, 100);

        btnServicio.setBackground(new java.awt.Color(255, 255, 255));
        btnServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnServicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnServicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnServicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnServicioMouseExited(evt);
            }
        });
        btnServicio.setLayout(null);

        txt_imgServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Servicios.png"))); // NOI18N
        btnServicio.add(txt_imgServicio);
        txt_imgServicio.setBounds(70, 10, 120, 80);

        txt_Servicio.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        txt_Servicio.setText("Servicios");
        txt_Servicio.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnServicio.add(txt_Servicio);
        txt_Servicio.setBounds(50, 70, 130, 30);

        jP_Principal.add(btnServicio);
        btnServicio.setBounds(650, 480, 190, 100);

        getContentPane().add(jP_Principal);
        jP_Principal.setBounds(0, 0, 900, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void BotonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseEntered
        BotonSalir.setBackground( new java.awt.Color (255,0,0) );
    }//GEN-LAST:event_BotonSalirMouseEntered

    private void BotonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSalirMouseExited
        BotonSalir.setBackground( new java.awt.Color(0,153,0) );
    }//GEN-LAST:event_BotonSalirMouseExited

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
        Conexion.cerrarBD();
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void btnClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseClicked
        clientes = new VistaClientes (this, this.cedula, this.permisos, this.nombre);
        clientes.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnClienteMouseClicked

    private void btnClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseEntered
        txt_imgCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cliente2.png")));
        txt_imgCliente.setLocation(50, 0);
        btnCliente.setBackground( new java.awt.Color (255,255,0) );
    }//GEN-LAST:event_btnClienteMouseEntered

    private void btnClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteMouseExited
         txt_imgCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cliente.png")));
         txt_imgCliente.setLocation(70, 0);
         btnCliente.setBackground( new java.awt.Color(255,255,255) );
    }//GEN-LAST:event_btnClienteMouseExited

    private void btnVeterinarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeterinarioMouseClicked
        veterinarios = new VistaVeterinario( this, this.cedula, this.permisos, this.nombre );
        veterinarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVeterinarioMouseClicked

    private void btnVeterinarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeterinarioMouseEntered
        // txt_imgCliente1
        txt_imgVeterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Veterinario2.png")));
        txt_imgVeterinario.setLocation(70, 0);
        btnVeterinario.setBackground( new java.awt.Color (255,255,0) );
    }//GEN-LAST:event_btnVeterinarioMouseEntered

    private void btnVeterinarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVeterinarioMouseExited
        // TODO add your handling code here:
         txt_imgVeterinario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Veterinario.png")));
        txt_imgVeterinario.setLocation(90, 0);
        btnVeterinario.setBackground( new java.awt.Color (255,255,255) );
    }//GEN-LAST:event_btnVeterinarioMouseExited

    private void btnEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadoMouseClicked
        empleados = new VistaEmpleado (this, this.cedula, this.permisos, this.nombre);
        empleados.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEmpleadoMouseClicked

    private void btnEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadoMouseEntered
        txt_imgEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Empleados2.png")));
        txt_imgEmpleado.setLocation(50, -10); 
        btnEmpleado.setBackground( new java.awt.Color (255,255,0) );
    }//GEN-LAST:event_btnEmpleadoMouseEntered

    private void btnEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmpleadoMouseExited
       txt_imgEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Empleados.png")));
       txt_imgEmpleado.setLocation(70, 0);
       btnEmpleado.setBackground( new java.awt.Color (255,255,255) );
    }//GEN-LAST:event_btnEmpleadoMouseExited

    private void btnMascotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMascotaMouseClicked
        mascotas = new VistaMascota (this, this.cedula, this.permisos, this.nombre) ;
        mascotas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMascotaMouseClicked

    private void btnMascotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMascotaMouseEntered
        
        txt_imgMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mascota2.png")));
        txt_imgMascota.setLocation(50, 0); 
        btnMascota.setBackground( new java.awt.Color (255,255,0) );
    }//GEN-LAST:event_btnMascotaMouseEntered

    private void btnMascotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMascotaMouseExited
        txt_imgMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mascota.png")));
        txt_imgMascota.setLocation(70, 0); 
        btnMascota.setBackground( new java.awt.Color (255,255,255) );
    }//GEN-LAST:event_btnMascotaMouseExited

    private void btnConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaMouseClicked
        consultas = new VistaConsultas (this, this.cedula, this.permisos, this.nombre);
        consultas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnConsultaMouseClicked

    private void btnConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaMouseEntered
        txt_imgConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Consulta2.png")));
        txt_imgConsultas.setLocation(50, 0); 
        btnConsulta.setBackground( new java.awt.Color (255,255,0) );
    }//GEN-LAST:event_btnConsultaMouseEntered

    private void btnConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaMouseExited
        txt_imgConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Consulta.png")));
        txt_imgConsultas.setLocation(70, 0); 
        btnConsulta.setBackground( new java.awt.Color (255,255,255) );
    }//GEN-LAST:event_btnConsultaMouseExited

    private void btnEspeciesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEspeciesMouseClicked
        especie = new VistaEspecie( this, this.cedula, this.permisos, this.nombre);
        especie.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEspeciesMouseClicked

    private void btnEspeciesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEspeciesMouseEntered
        txt_imgEspecies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Especies2.png")));
        txt_imgEspecies.setLocation(50, 0); 
        btnEspecies.setBackground( new java.awt.Color (255,255,0) );
    }//GEN-LAST:event_btnEspeciesMouseEntered

    private void btnEspeciesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEspeciesMouseExited
        txt_imgEspecies.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Especies.png")));
        txt_imgEspecies.setLocation(70, 0); 
        btnEspecies.setBackground( new java.awt.Color (255,255,255) );
    }//GEN-LAST:event_btnEspeciesMouseExited

    private void btnFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturaMouseClicked
        facturas = new VistaFactura (this, this.cedula, this.permisos, this.nombre);
        facturas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnFacturaMouseClicked

    private void btnFacturaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturaMouseEntered
        txt_imgFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Factura2.png")));
        txt_imgFactura.setLocation(50, 0); 
        btnFactura.setBackground( new java.awt.Color (255,255,0) );
    }//GEN-LAST:event_btnFacturaMouseEntered

    private void btnFacturaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturaMouseExited
        txt_imgFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Factura.png")));
        txt_imgFactura.setLocation(70, 0); 
        btnFactura.setBackground( new java.awt.Color (255,255,255) );
    }//GEN-LAST:event_btnFacturaMouseExited

    private void btnEspecialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEspecialidadMouseClicked
        especialidad = new VistaEspecialidad(this, this.cedula, this.permisos, this.nombre );
        especialidad.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEspecialidadMouseClicked

    private void btnEspecialidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEspecialidadMouseEntered
      txt_imgEspecialidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Especialidad2.png")));
      txt_imgEspecialidad.setLocation(70, 0); 
       btnEspecialidad.setBackground( new java.awt.Color (255,255,0) );
    }//GEN-LAST:event_btnEspecialidadMouseEntered

    private void btnEspecialidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEspecialidadMouseExited
       txt_imgEspecialidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Especialidad.png")));
       txt_imgEspecialidad.setLocation(90, 0); 
       btnEspecialidad.setBackground( new java.awt.Color (255,255,255) );
    }//GEN-LAST:event_btnEspecialidadMouseExited

    private void btnServicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicioMouseClicked
        servicios = new VistaServicios ( this, this.cedula, this.permisos, this.nombre ) ; 
        servicios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnServicioMouseClicked

    private void btnServicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicioMouseEntered
        txt_imgServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Servicios2.png")));
        txt_imgServicio.setLocation(50, 0); 
        btnServicio.setBackground( new java.awt.Color (255,255,0) );
    }//GEN-LAST:event_btnServicioMouseEntered

    private void btnServicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServicioMouseExited
        txt_imgServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Servicios.png")));
        txt_imgServicio.setLocation(70, -10); 
        btnServicio.setBackground( new java.awt.Color (255,255,255) );
    }//GEN-LAST:event_btnServicioMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel Txt_Ingreso;
    private javax.swing.JLabel Txt_Ingreso1;
    private javax.swing.JLabel Txt_user;
    private javax.swing.JPanel btnCliente;
    private javax.swing.JPanel btnConsulta;
    private javax.swing.JPanel btnEmpleado;
    private javax.swing.JPanel btnEspecialidad;
    private javax.swing.JPanel btnEspecies;
    private javax.swing.JPanel btnFactura;
    private javax.swing.JPanel btnMascota;
    private javax.swing.JPanel btnServicio;
    private javax.swing.JPanel btnVeterinario;
    private javax.swing.JPanel jP_Principal;
    private javax.swing.JPanel jp_BarraHerramientas;
    private javax.swing.JLabel txt_Cliente;
    private javax.swing.JLabel txt_Cliente2;
    private javax.swing.JLabel txt_Consulta;
    private javax.swing.JLabel txt_Empleado;
    private javax.swing.JLabel txt_Especiali;
    private javax.swing.JLabel txt_Especie;
    private javax.swing.JLabel txt_Factura;
    private javax.swing.JLabel txt_Servicio;
    private javax.swing.JLabel txt_Veterinario;
    private javax.swing.JLabel txt_imgCliente;
    private javax.swing.JLabel txt_imgConsultas;
    private javax.swing.JLabel txt_imgEmpleado;
    private javax.swing.JLabel txt_imgEspecialidad;
    private javax.swing.JLabel txt_imgEspecies;
    private javax.swing.JLabel txt_imgFactura;
    private javax.swing.JLabel txt_imgMascota;
    private javax.swing.JLabel txt_imgServicio;
    private javax.swing.JLabel txt_imgVeterinario;
    // End of variables declaration//GEN-END:variables
   
    private void LimitarEmpleado() {
        btnEmpleado.setVisible(false);
        txt_Empleado.setVisible(false);
        txt_imgEmpleado.setVisible(false);
    }
    private void LimitarVeterinario() {
        btnVeterinario.setVisible(false);
        txt_Veterinario.setVisible(false);
        txt_imgVeterinario.setVisible(false);
    }
    private void LimitarEspecie() {
        btnEspecies.setVisible(false);
        txt_Especie.setVisible(false);
        txt_imgEspecies.setVisible(false);
    }
    private void LimitarFactura() {
        btnFactura.setVisible(false);
        txt_Factura.setVisible(false);
        txt_imgFactura.setVisible(false);
    }
    private void LimitarEspecialidad() {
        btnEspecialidad.setVisible(false);
        txt_Especiali.setVisible(false);
        txt_imgEspecialidad.setVisible(false);
    }
    private void Limitarservicios() {
        btnServicio.setVisible(false);
        txt_Servicio.setVisible(false);
        txt_imgServicio.setVisible(false);
    }
    private void LimitarConsultas() {
        btnConsulta.setVisible(false);
        txt_Consulta.setVisible(false);
        txt_imgConsultas.setVisible(false);
    }
    private void initMiscomponentes() {
        especialidad = new VistaEspecialidad(this );
        especie = new VistaEspecie( this);
        servicios = new VistaServicios ( this ) ; 
        clientes = new VistaClientes (this);
        empleados = new VistaEmpleado (this);
        veterinarios = new VistaVeterinario( this ); 
        mascotas = new VistaMascota (this) ;
        consultas = new VistaConsultas (this);
        facturas = new VistaFactura (this);
        
        if(permisos==1){
           
            //Limitar opciones
            LimitarEmpleado();
            LimitarVeterinario();
            LimitarEspecialidad();
            LimitarConsultas();
            btnCliente.setBounds(55, 233, 190, 100);
            btnMascota.setBounds(355, 233, 190, 100);
            btnEspecies.setBounds(655, 233, 190, 100);
            btnFactura.setBounds(173, 466, 190, 100);
            btnServicio.setBounds(536, 466, 190, 100);
        }
        if(permisos==2){
           
            //Limitar opciones
            LimitarEmpleado();
            LimitarVeterinario();
            LimitarFactura();
            LimitarEspecialidad();
            Limitarservicios();
            
            btnEspecies.setBounds(355, 440, 190, 100);
            btnCliente.setBounds(55, 320, 190, 100);
            btnMascota.setBounds(355, 320, 190, 100);
            btnConsulta.setBounds(655, 320, 190, 100);
        
        }
    }
}
